PREFIX prop: <http://dbpedia.org/property/>
SELECT *
WHERE
{
<http://dbpedia.org/resource/Amazon_River> prop:length ?amazon .
<http://dbpedia.org/resource/Nile> prop:length ?nile .
# FILTER(?amazon < ?nile) .
}