# filename: ex218.rq

PREFIX d: <http://learningsparql.com/ns/data#>
PREFIX dm: <http://learningsparql.com/ns/demo#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?s
FROM <ex217.ttl>
WHERE {
    ?s ?p "two"^^xsd:string .
    # FILTER (DATATYPE(?o) != xsd:integer)
}