# filename: ex141.rq

PREFIX e: <http://learningsparql.com/ns/expenses#>

SELECT ?mealCode ?amount
FROM <ex138.ttl>
WHERE {
    ?meal   e:description   ?description ;
            e:amount        ?amount .
    BIND (UCASE(SUBSTR(?description,1,3)) AS ?mealCode)
}