# filename: ex246.rq

BASE <http://learningsparql.com/ns/demo#>

# SELECT *
CONSTRUCT {?s ?p ?testURI . }
# FROM <ex241.ttl>
WHERE {
    ?s ?p ?o .
    BIND (URI(?o) AS ?testURI)
}

# 2024-10-06: "5 bucks" is not converted