# filename: ex082.rq

PREFIX c:  <http://learningsparql.com/ns/citation#>
PREFIX :   <http://learningsparql.com/ns/papers#>

SELECT DISTINCT ?s
WHERE {
    ?s c:cites/^c:cites  :paperF .
    FILTER(?s != :paperF)
}