# filename: ex130.rq

PREFIX ab: <http://learningsparql.com/ns/addressbook#>
PREFIX d: <http://learningsparql.com/ns/data#>

SELECT *
FROM NAMED <ex122.ttl>
FROM NAMED <ex125.ttl>
FROM <../part2/ex069.ttl>
WHERE {
    {
        ?course ab:courseTitle ?courseName .
    }
    UNION
    {
        GRAPH ?g {
            ?course ab:courseTitle ?courseName .
        }
    }
}