# filename: ex287.rq

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX d: <http://learningsparql.com/ns/data#>

SELECT *
FROM <ex284.ttl>
WHERE {
    ?s rdfs:label   ?label .
    BIND (STRSTARTS(?label, "12") AS ?strstartsTest)
    BIND (STRENDS(?label,"ing") AS ?strendsTest)
    BIND (CONTAINS(?label, " ") AS ?containsTest)
    BIND (regex(?label, "\\d{5}") AS ?regexTest)
}