# filename: ex216.rq

PREFIX d: <http://learningsparql.com/ns/data#>
PREFIX ab: <http://learningsparql.com/ns/addressbook#>

# DESCRIBE <http://learningsparql.com/ns/data#course59>
# SELECT *
DESCRIBE ?course
WHERE {
    d:i0432 ab:takingCourse ?course .
}