# filename: ex274.rq

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label ?strippedLabel
FROM <ex037.ttl>
WHERE {
    ?s rdfs:label ?label .
    FILTER (lang(?label) = 'fr' || lang(?label) = 'en')
    BIND (str(?label) AS ?strippedLabel)
}